In [145]:
#Import the numpy library
import numpy as np

#### A. Defining a 1D numpy array

In [7]:
[1, 1.0, '1']

[1, 1.0, '1']

In [2]:
l = [12, 34, 56, 78, 90]

In [3]:
type(l)

list

In [5]:
x = np.array(l)
x

array([12, 34, 56, 78, 90])

In [6]:
type(x)

numpy.ndarray

In [8]:
l

[12, 34, 56, 78, 90]

In [9]:
np.array([1, 1.0, '1'])

array(['1', '1.0', '1'], dtype='<U32')

In [10]:
np.array([1, 1.4, 6])

array([1. , 1.4, 6. ])

#### B. Creating Regular Sequence

In [11]:
#Create a regular sequence of integers starting from 1 to 10. integers = c(1,2,3,4,.......,10)

integers = np.arange(1, 11, 1)
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Create a regular sequence of integers starting from 10 to 1.

integers = np.arange(10, 0, -1)
integers

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
#Create a regular sequence of even integers between 10 to 20

even = np.arange(10, 21, 2)
even

array([10, 12, 14, 16, 18, 20])

In [14]:
#Create a regular sequence of the following type: [10.0,10.5,11.0,11.5, ... , 19.5, 20.0]

sequence = np.arange(10, 21, 0.5)
sequence

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [15]:
#Create a regular sequence of length 20 ranging from 0 to 5

np.linspace(start = 0, stop = 5, num = 20, endpoint = True)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.linspace(start = 0, stop = 1, num = 100, endpoint = False)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [ ]:
#Help for np.linspace

help(np.linspace)           # shift+tab

In [146]:
#Studying the arange function

help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

#### C. Creating a Random Sequence

In [19]:
#Generate 20 random numbers between 1 and 100

np.random.seed(5)
a = np.random.randint(1, 100, 20)                 # will pick 20 random numbers from 1 to 100
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8, 77, 16, 54, 81, 28, 45, 78,
       76, 66, 48])

In [20]:
np.random.seed(0)
b = np.random.random(20)
b

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [21]:
l = [1, 5, 7, 3, 8, 2, 6]

#Shuffle the vector x

x = np.array(l)
np.random.shuffle(x)                              # it will shuffle the array x
x

array([8, 6, 2, 5, 1, 3, 7])

In [22]:
np.random.choice(l, 2)                            # chooses 2 random numbers from the array l

array([3, 6])

In [23]:
np.random.choice(x, 15, replace=True)             # with replacement

array([8, 6, 6, 6, 8, 2, 1, 5, 7, 5, 2, 1, 2, 8, 8])

In [25]:
np.random.choice(x, 15, replace = False)          # without replacement it will give error

ValueError: Cannot take a larger sample than population when 'replace=False'

In [149]:
#Permute x and return it

x = np.random.permutation(10)
x

array([7, 1, 2, 0, 5, 6, 8, 3, 9, 4])

To find more on numpy random sampling Go To this link 
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html 

#### D. Some basic numpy methods

In [30]:
x = np.array([12,34,24,45,7.8,18])

In [27]:
#Size of the array
x.size

6

In [28]:
len(x)

6

In [31]:
#data type
x.dtype

dtype('float64')

In [32]:
#Type of the object
type(x)

numpy.ndarray

In [34]:
#Type conversion
x = x.astype(int)                       # will update the x
x

array([12, 34, 24, 45,  7, 18])

In [35]:
x.astype(str)                           # not updating x

array(['12', '34', '24', '45', '7', '18'], dtype='<U11')

#### E. Some basic (1D) numpy operations

In [36]:
#Consider that we have two arrays

x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [44]:
a = [1, 2, 3]
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [37]:
#Addition
x + y

array([15, 40, 32, 50,  8, 28])

In [39]:
y + 10

array([13, 16, 18, 15, 11, 20])

In [38]:
#Subtraction
x - y

array([ 9, 28, 16, 40,  6,  8])

In [40]:
#Multiplication by scalar
10 * y

array([ 30,  60,  80,  50,  10, 100])

In [45]:
y

array([ 3,  6,  8,  5,  1, 10])

In [41]:
y * (1/10)

array([0.3, 0.6, 0.8, 0.5, 0.1, 1. ])

In [42]:
y / 10

array([0.3, 0.6, 0.8, 0.5, 0.1, 1. ])

In [43]:
#Element wise multiplication (dot product)
x * y

array([ 36, 204, 192, 225,   7, 180])

In [46]:
#Using dot method
x.dot(y)

844

In [47]:
y.dot(x)

844

In [48]:
np.dot(x, y)

844

In [49]:
np.sum(x*y)

844

In [50]:
print(x)
print(y)

[12 34 24 45  7 18]
[ 3  6  8  5  1 10]


In [51]:
x**(1/2)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [53]:
np.sqrt(x)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [52]:
#Squaring each elements in an array
x**2

array([ 144, 1156,  576, 2025,   49,  324], dtype=int32)

In [54]:
np.exp(x)

array([1.62754791e+05, 5.83461743e+14, 2.64891221e+10, 3.49342711e+19,
       1.09663316e+03, 6.56599691e+07])

#### F. Some Useful Numpy Functions

In [55]:
y = np.array([3,6,8,5,1,10])

In [58]:
unit = np.array([1,1,1,1,1,1])

In [59]:
unit.dot(y)

33

In [60]:
#Sum
np.sum(y)

33

In [61]:
sum(y)

33

In [63]:
#Mean
np.mean(y)

5.5

In [ ]:
#Standard Deviation
np.std(y)

In [ ]:
#Minimum
np.min(y)

In [ ]:
#Maximum
np.max(y)

In [64]:
#Percentiles
np.percentile(y, 60)

6.0

In [65]:
np.percentile(y, [25, 62, 75])

array([3.5, 6.2, 7.5])

In [66]:
#Sorting
np.sort(y)

array([ 1,  3,  5,  6,  8, 10])

In [67]:
y

array([ 3,  6,  8,  5,  1, 10])

In [68]:
-y

array([ -3,  -6,  -8,  -5,  -1, -10])

In [69]:
np.sort(-y)

array([-10,  -8,  -6,  -5,  -3,  -1])

In [70]:
-np.sort(-y)

array([10,  8,  6,  5,  3,  1])

#### G. Subsetting a 1D numpy array

In [152]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [71]:
#Subsetting and slicing is same as list
x[0]

12

In [72]:
x[1]

34

In [73]:
y[3]

5

In [153]:
x[len(x)-1]

18

In [75]:
x[3:5]

array([45,  7])

In [76]:
x[[2,4]]

array([24,  7])

#### H. Conditional Subsetting

**The Comparison Operators**

      > is greater than
      < is less than
      == is equal to
      <= is less than equal to
      >= is greater than equal to

In [156]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [79]:
2 > 30

False

In [78]:
x > 20

array([False,  True,  True,  True, False, False])

In [80]:
np.sum(x > 20)

3

In [81]:
x[x > 20]                 # Conditional subsetting

array([34, 24, 45])

In [157]:
x > y

array([ True,  True,  True,  True,  True,  True])

**The Logical Operators**

    AND: &
    OR : |

In [88]:
x

array([12, 34, 24, 45,  7, 18])

In [86]:
(x > 30) | (x < 10)

array([False,  True, False,  True,  True, False])

In [87]:
(x > 10) & (x < 30)

array([ True, False,  True, False, False,  True])

In [89]:
True | False

True

In [90]:
True & False

False

**Problems**

In [159]:
#Consider the following two vectors

x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

In [94]:
#a. Vaues of x that are less than 35

# x < 35
x[x < 35]

array([33, 23])

In [95]:
#b. The number of observations in y that are more than 150

np.sum(y > 150)
# y[y>150].sum

2

In [161]:
#OR
y[y>150].sum

<function ndarray.sum>

In [96]:
#c. The number of observations in y that are between 120 and 165

np.sum((y >= 120) & (y <= 165))

4

In [99]:
#d. The vaues in x that are less than 30 or greater than 50

x[(x < 30) | (x > 50)]

array([23, 67, 54])

In [100]:
#e. The values in x for which the values in y is less than or equal to 120
x[y <= 120]

array([33, 67])

In [102]:
#f. The values in y for which the values in x is equal to 45
y[x == 45]

array([151])

#### I. Defining a 2D numpy array

In [103]:
#Converting a 1D array into 2D array
x = np.array([33,45,23,67,54,48])

matrix = x.reshape(2,3)
matrix

array([[33, 45, 23],
       [67, 54, 48]])

In [105]:
matrix = x.reshape(3,2)
matrix

array([[33, 45],
       [23, 67],
       [54, 48]])

In [106]:
#Create a 3x3 matrix containing elements from 1 to 9
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
#Joining two 1D arrays to form a matrix
x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

matrix = np.array([x,y])
matrix

array([[ 33,  45,  23,  67,  54,  48],
       [108, 151, 164, 119, 135, 122]])

#### J. Some basic methods for 2D numpy array

In [109]:
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [110]:
type(matrix)

numpy.ndarray

In [111]:
#Checking the shape of the matrix
matrix.shape

(5, 3)

In [112]:
#Dimension of the array
matrix.ndim

2

In [113]:
#Data type of the elements in the array
matrix.dtype

dtype('int32')

In [115]:
matrix.dtype.name

'int32'

In [114]:
#Number of elements present in the matrix
matrix.size

15

In [116]:
#Size of the matrix in bytes
matrix.itemsize

4

#### K. Subsetting 2D numpy array

In [203]:
#matrix
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [118]:
#a) Print the first element of the matrix.

matrix[0,0]

38

In [119]:
#b) Print the last element of the matrix.
matrix[matrix.shape[0]-1,matrix.shape[1]-1]

43

In [120]:
#Or
matrix[-1,-1]

43

In [122]:
#c) Print the values of the first row.
matrix[0,:]

array([38, 33, 47])

In [124]:
#d) Print the values of the fourth row.
matrix[3, :]

array([38, 44, 21])

In [125]:
#e) Print the values first column.
matrix[:, 0]

array([38, 29, 21, 38, 28])

In [192]:
#f) Calculate the total of the third row.
a=np.sum(matrix, axis = 1)
#np.sum(matrix[2:3], axis=1)
a[2]

102

In [191]:
#g) Calculate the total of the fifth row.
a = np.sum(matrix, axis=1)
#np.sum(matrix[4:5], axis=1)
a[4]

97

In [193]:
#h) Calculate the total of the second column.
b=np.sum(matrix, axis=0)
b[1]

185

In [195]:
#i) Calculate the average of the values of the first row.
c=np.mean(matrix, axis=1)
c[0]

39.333333333333336

In [197]:
#j) Replace the first value of the matrix by 50.

matrix[0,0] = 50
matrix

array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [198]:
#k) Replace the last value of the matrix by 30.

matrix[-1,-1] = 30
matrix

array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 30]])

In [204]:
#l) Replace the second column of the matrix by the vector (20,30,20,30,20)

#matrix[:1] = [20,30,20,30,20]
matrix[:1]


array([[38, 33, 47]])

In [201]:
#m) Replace the first row of the matrix by the vector its average (calculated above).


matrix[0:] = np.mean(matrix, axis=0)
matrix

array([[33, 37, 36],
       [33, 37, 36],
       [33, 37, 36],
       [33, 37, 36],
       [33, 37, 36]])

In [182]:
#q) Calculate the sum of all the elements of the matrix

np.sum(matrix)

532

In [184]:
#r) Calculate the sum of all the rows on the matrix

np.sum(matrix, axis=1)

array([118, 112, 102, 103,  97])

In [185]:
#s) Calculate the sum of all the colummns of the matrix

np.sum(matrix, axis=0)

array([154, 185, 193])

#### L. Matrix Operations

In [126]:
#Defining a matrix 'm'
m = np.array([[2,3],[4,5]])
m

array([[2, 3],
       [4, 5]])

In [127]:
#Defining a matrix 'n'
n = np.array([[1,0],[3,6]])
n

array([[1, 0],
       [3, 6]])

In [128]:
#Multiplication by scalar
2*n

array([[ 2,  0],
       [ 6, 12]])

In [129]:
#Matrix addition
m + n

array([[ 3,  3],
       [ 7, 11]])

In [130]:
#Matrix Multilication
np.dot(m, n)

array([[11, 18],
       [19, 30]])

In [131]:
#Preferred - for Matrix Multilication
np.matmul(m, n)

array([[11, 18],
       [19, 30]])

In [132]:
#Preferred - for Matrix Multilication
m @ n

array([[11, 18],
       [19, 30]])

In [133]:
#Element-wise array multilication
np.multiply(m, n)

array([[ 2,  0],
       [12, 30]])

In [134]:
m*n

array([[ 2,  0],
       [12, 30]])

#### Copying data

In [135]:
p = np.array([2,5,8,6])

In [136]:
q = p          # new object is not created i.e. memory location is same for p and q, any change in q reflects in p

In [137]:
q

array([2, 5, 8, 6])

In [139]:
q[2] = 10
q

array([ 2,  5, 10,  6])

In [140]:
p

array([ 2,  5, 10,  6])

In [141]:
q = p.copy()       # new object is created, change in q wont reflect in p

In [142]:
q

array([ 2,  5, 10,  6])

In [143]:
q[2] = 50
q

array([ 2,  5, 50,  6])

In [144]:
p

array([ 2,  5, 10,  6])